services:
  frontend:
    build:
      context: ./horario-project
    container_name: horario_frontend
    ports:
      - "3000:80"
    volumes:
      - ./horario-project:/app
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 👈 Añadido para acceso al host

  db:
    image: postgres:15
    container_name: mi_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./Horario_API/.env
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
